name: Build (Development)

on:
  push:
    branches: [ dev ]

jobs:
  build-development:
    uses: ./.github/workflows/build.yml
    with:
      base_image: docker.io/library/fedora:36
      release: false
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
