name: Build (Development)

on:
  push:
    branches: [ dev ]

jobs:
  build-dev:
    uses: ./.github/workflows/build.yml
    with:
      base_image: docker.io/library/fedora:36
      # TODO remove after finishing testing
      release: true
    secrets:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}
