name: Build (Release)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      base_image: docker.io/library/fedora:36
      release: true
    secrets:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}
