name: Build (Release)

on:
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      ref: main
      tags: "ghcr.io/${{ github.repository }}:latest"
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
