name: Build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      tags:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: QEMU Setup
        uses: docker/setup-qemu-action@v2

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2

      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ inputs.tags }}
