name: Build (Release)

on:
  push:
    tags: [ '*' ]

jobs:
  build-release:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}
      tags: "${{ github.repository }}:${{ github.ref }},${{ github.repository }}:latest"
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
