name: Build (Release)

on:
  push:
    tags: [ '*' ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    uses: ./build.yml@main
    with:
      ref: ${{ github.ref }}
      tags: "${{ github.repository }}:${{ github.ref }},${{ github.repository }}:latest"
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
