name: Build (Development)

on:
  push:
    branches: [ main ]

jobs:
  build-development:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}
      tags: "ghcr.io/${{ github.repository }}:development"
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
